import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { createBridge, createController, SNAPSHOT_VALID_SECONDS } from './controller.mjs';

const controller=createController(createBridge(process.env.WORKBUDDY_COMPUTER_PYTHON));
const server=new McpServer({name:'workbuddy-windows-computer-tools',version:'0.5.0'});
const appName=z.enum(['firefox','chrome','edge','notepad']);
const windowId=z.string().regex(/^\d+$/).max(20).describe('Window ID returned by desktop_windows.');
const snapshotId=z.string().uuid().describe(`Fresh single-use snapshot_id returned by desktop_observe; expires after ${SNAPSHOT_VALID_SECONDS} seconds. Observe again if the content changed.`);
const screenSnapshotId=z.string().uuid().describe(`Fresh single-use snapshot_id returned specifically by desktop_screen_observe; expires after ${SNAPSHOT_VALID_SECONDS} seconds.`);
const mutation={readOnlyHint:false,destructiveHint:true,idempotentHint:false,openWorldHint:true};
const wrap=handler=>async args=>{try{return{content:[{type:'text',text:JSON.stringify(await handler(args),null,2)}]};}catch(error){return{isError:true,content:[{type:'text',text:error.message}]};}};
server.registerTool('desktop_find_app',{description:'Find an installed supported app using Windows App Paths registry, common install folders and PATH. A missing PATH entry does not mean uninstalled. Read-only; never installs software.',inputSchema:{app:appName},annotations:{readOnlyHint:true,openWorldHint:false}},wrap(controller.findApp));
server.registerTool('desktop_launch',{description:'Launch the user-requested supported application by discovered absolute executable, no shell or custom arguments. Browsers open a NEW window with an optional HTTP(S) URL; existing windows are preserved. Only launch for an authorized task. Returns process-start and new-window evidence, NOT proof of page load. If no new window appears, inspect before retrying. STOP blocks launch.',inputSchema:{app:appName,url:z.string().max(2000).optional().describe('HTTP(S) URL without credentials, spaces or controls. Omit for blank browser window. Not supported for notepad.')},annotations:mutation},wrap(controller.launch));
server.registerTool('desktop_browser_state',{description:'Read selected Firefox/Chrome/Edge window title and, if exposed by UI Automation, browser chrome address bar URL. Does not inspect web document fields, passwords or clipboard. URL may be null; title/URL alone do not verify loaded page content. No focus/input changes.',inputSchema:{window_id:windowId},annotations:{readOnlyHint:true,openWorldHint:false}},wrap(controller.browserState));
server.registerTool('desktop_windows',{description:'List all visible desktop windows in front-to-back z_order with IDs, owner-window relationships, enabled/minimized state, titles, processes and bounds. Use the IDs to move between multiple windows and identify blocking popups. Window titles may contain private information.',inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:false}},wrap(controller.windows));
server.registerTool('desktop_cursor',{description:'Read the current absolute pointer position and foreground window. Read-only diagnostic for recovering from transient menus, popups, or a focus mismatch; never infers a click target.',inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:false}},wrap(controller.cursor));
server.registerTool('desktop_open_tray',{description:'Open the Windows system tray hidden-icons popup for a user-requested task, without moving the mouse. Prefer this for "open system tray" or "show hidden icons". Uses Win+B, verifies the hidden-icons chevron has focus, then presses Enter. If already open, leaves it open. No snapshot or coordinates needed. Returns opened=true only when the Explorer overflow window is visible; otherwise observe the screen and click the visible chevron. Observe the screen before selecting a tray icon. Invalidates earlier snapshots; STOP and corner pause remain active.',inputSchema:{},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false}},wrap(controller.openTray));
server.registerTool('desktop_focus',{description:'Restore and raise one user-chosen window without typing. If it owns a visible active popup, activates that popup and returns activated_window_id for the next observation. Call again with another ID to move between windows. Returns focused=false with recovery guidance when Windows denies keyboard focus; does not bypass elevation rules.',inputSchema:{window_id:windowId},annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false}},wrap(controller.focus));
server.registerTool('desktop_observe',{description:'Screenshot only the chosen foreground window. Returns an image and a fresh single-use snapshot ID; use image-pixel coordinates. Screenshots can contain private data. Do not capture unrelated windows.',inputSchema:{window_id:windowId},annotations:{readOnlyHint:true,openWorldHint:false}},async args=>{
  try{const result=await controller.observe(args);return{content:[{type:'text',text:JSON.stringify(result.metadata,null,2)},{type:'image',data:result.png_base64,mimeType:'image/png'}]};}
  catch(error){return{isError:true,content:[{type:'text',text:error.message}]};}
});
server.registerTool('desktop_screen_observe',{description:'Screenshot the whole virtual desktop, including every monitor, visible windows, taskbar, notification area and open shell flyouts. Use this to locate a tray/taskbar control or switch between visible windows. Returns a fresh single-use snapshot ID; coordinates are pixels in the returned image. Screenshots can contain private data.',inputSchema:{},annotations:{readOnlyHint:true,openWorldHint:false}},async()=>{
  try{const result=await controller.screenObserve();return{content:[{type:'text',text:JSON.stringify(result.metadata,null,2)},{type:'image',data:result.png_base64,mimeType:'image/png'}]};}
  catch(error){return{isError:true,content:[{type:'text',text:error.message}]};}
});
server.registerTool('desktop_screen_click',{description:'Click a taskbar, notification-area, shell-flyout, or visible-window target using pixels from a fresh desktop_screen_observe image. Negative-position monitors are handled internally. The observation is single-use; observe the screen again after clicking to verify the result. Prefer desktop_click for controls inside an already selected window. This can trigger consequential UI actions; obtain user approval where needed.',inputSchema:{snapshot_id:screenSnapshotId,x:z.number().int().min(0),y:z.number().int().min(0),button:z.enum(['left','right']).default('left'),count:z.number().int().min(1).max(2).default(1)},annotations:mutation},wrap(args=>controller.screenClick(args)));
server.registerTool('desktop_click',{description:'Click an observed target using screenshot pixels. Requires a fresh snapshot and unchanged foreground/bounds. This can trigger consequential UI actions: obtain user approval where needed, and observe again afterward.',inputSchema:{snapshot_id:snapshotId,x:z.number().int().min(0),y:z.number().int().min(0),button:z.enum(['left','right']).default('left'),count:z.number().int().min(1).max(2).default(1)},annotations:mutation},wrap(args=>controller.act('click',args)));
server.registerTool('desktop_type_text',{description:'Type up to 2000 Unicode characters into the focused control, without clipboard use or pressing Enter. No newlines/control characters. Confirm the target field from a fresh screenshot. Terminal/developer-console input is blocked.',inputSchema:{snapshot_id:snapshotId,text:z.string().max(2000).refine(value=>!/[\x00-\x1f\x7f]/.test(value))},annotations:mutation},wrap(args=>controller.act('type',args)));
server.registerTool('desktop_key',{description:'Press one supported editing/navigation shortcut. Ctrl+L focuses the address bar (supported browsers only). Enter or Ctrl+S can submit/save changes; confirm intent before consequential actions. A fresh screenshot is required.',inputSchema:{snapshot_id:snapshotId,key:z.enum(['ENTER','TAB','ESC','BACKSPACE','DELETE','UP','DOWN','LEFT','RIGHT','HOME','END','PAGEUP','PAGEDOWN','CTRL+A','CTRL+F','CTRL+L','CTRL+S','CTRL+Z','CTRL+Y','SHIFT+TAB'])},annotations:mutation},wrap(args=>controller.act('key',args)));
server.registerTool('desktop_scroll',{description:'Move the pointer to x,y in the observed screenshot and scroll that content area without clicking. Use image-pixel coordinates inside the intended scrollable pane, not the toolbar or address bar. Positive amount is up, negative is down, 1 to 5 wheel notches. Input delivery does not prove content moved: observe again and compare. Do not repeatedly scroll an unchanged pane.',inputSchema:{snapshot_id:snapshotId,x:z.number().int().min(0).describe('Horizontal pixel within the returned screenshot, targeting the scrollable content.'),y:z.number().int().min(0).describe('Vertical pixel within the returned screenshot, targeting the scrollable content.'),amount:z.number().int().min(-5).max(5).refine(value=>value!==0)},annotations:mutation},wrap(args=>controller.act('scroll',args)));
await server.connect(new StdioServerTransport());
